[feature] add openai edge api
gohandao/ai-traveler pull request #21
Opened 2023-02-27 02:39 UTC by mrgishi

## issue番号　#xxx
## 変更内容
- 必要パッケージ追加
- エッジAPI追加
- 古いAPI削除

## 確認して欲しい箇所
- []

## その他

2023-02-27 13:42 UTC, Bayathy requested changes

2023-02-27 13:42 UTC, Bayathy commented on src/lib/openaiStream.ts
> +}
ここってinterfeceじゃなきゃ駄目な感じですかね？ほかはtypesなので

あとは命名規則ミスってるかもです

2023-02-27 13:42 UTC, Bayathy commented on src/lib/openaiStream.ts
> +      for await (const chunk of res.body as any) {
片付け難しい場合はdisableしてもらっても大丈夫です！

2023-02-28 10:21 UTC, mrgishi commented on src/lib/openaiStream.ts
> +      for await (const chunk of res.body as any) {
OKです！

2023-02-28 10:27 UTC, mrgishi commented on src/lib/openaiStream.ts
> +}
参照コードのままでした！
→Typesに修正
命名規則やっぱ接頭辞のTなくていいかもなぁ。

2023-02-28 11:00 UTC, katayama8000 commented
前のプロジェクトでも聞いた気がしますが、 `lib`、`utils`はどう使い分けているのでしたっけ？

2023-02-28 11:01 UTC, katayama8000 commented on src/utils/getEdgeAiStream.ts
> +  let done = false
細かいですがletの場合は
```ts
let isDone: boolean = false
```
にしたい。
任せます！

2023-02-28 12:52 UTC, mrgishi commented on src/utils/getEdgeAiStream.ts
> +  let done = false
この辺も元コードのままでした。
letは警告出したいかもです。

lib>外部ライブラリの中継
utils>直接機能する関数

2023-03-01 10:02 UTC, katayama8000 approved these changes
![LGTM](https://image.lgtmoon.dev/199133)

2023-03-06 22:05 UTC, Bayathy approved these changes

2023-03-09 10:03 UTC, merged