feat; create Prisma API wrapper
gohandao/ai-traveler pull request #28
Opened 2023-03-20 03:44 UTC by Bayathy

## issue番号　#xxx
## 変更内容
PlanetScaleに書き込む関数の作成

## 確認して欲しい箇所

- [] 

## その他

2023-04-02 01:40 UTC, katayama8000 commented
`npx prisma generate`を実行する必要ある。

2023-04-02 01:44 UTC, katayama8000 commented
`get`と`post`は正常動作している。(errorが帰ってくるまで確認できた)

2023-04-02 01:45 UTC, katayama8000 commented
`post`が正常動作するcurlコマンドとかわかれば教えて欲しいです！
postmanに書いてあるはず。

2023-04-02 01:46 UTC, katayama8000 requested changes

2023-04-02 01:46 UTC, katayama8000 commented on src/pages/api/prisma.page.ts
> +  const data: Prisma.HistoryCreateInput = req.body
型エラーになってます。
Prismaの型定義ファイルに`HistoryCreateInput`なさそう？

2023-04-05 09:19 UTC, Bayathy commented on src/pages/api/prisma.page.ts
> +  const data: Prisma.HistoryCreateInput = req.body
たぶんエディタ側で反映されてないだけかもしれません。新しくクローンしたディレクトリでもここでエラーは出なかったので

2023-04-09 02:56 UTC, katayama8000 commented
`npx prisma studio`で動作確認できる

2023-04-09 03:05 UTC, katayama8000 approved these changes
よさよさ

2023-04-09 05:54 UTC, merged